INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(1, 'Moore-Watson', '4 Mitchell turnpike', 'West Damianside', 'NN55 9UF', '+44(0)289018562', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(2, 'Doyle PLC', '45 Brian hills', 'Leahport', 'G29 3HY', '+441632 960 169', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(3, 'Haynes-Holloway', '6 Carey ville', 'Lake Edwardborough', 'S4 9YJ', '+441632 960 169', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(4, 'Brown-Chamberlain', '573 Clifford lights', 'Joshuafurt', 'M9 5UB', '+44(0)1914960707', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(5, 'Randall Chapman and Jones', '40 Moore prairie', 'New James', 'CA14 9QE', '9098790351', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(6, 'Holmes Group', '103 Daniel grove', 'Davieshaven', 'OL7 6FL', '292018860', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(7, 'Yates-Jarvis', '8 Johnson branch', 'Port Pamela', 'SO36 3NQ', '+44114 4960308', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(8, 'Bibi PLC', '2 Christopher way', 'Lake Kimfurt', 'KT21 3DZ', '+44(0)113 4960032', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(9, 'Stewart Wright and Davies', '05 Kenneth lodge', 'West Kate', 'E8D 7WH', '028 9018 0368', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(10, 'Schofield and Sons', '7 Jill port', 'Swifttown', 'L9 2HQ', '0113 4960754', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(11, 'Evans Parker and Harper', '031 Tucker cliff', 'New Katemouth', 'M5G 2GJ', '(0113) 4960043', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(12, 'Jenkins-Williams', '7 Leon locks', 'Joannahaven', 'PH2 3RW', '+44(0)1632960784', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(13, 'King Singh and Waters', '0 Glenn crossing', 'Thomasstad', 'E4 6TH', '0113 496 0659', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(14, 'Davies Adams and Clayton', '1 Leon brook', 'Lewisbury', 'E87 1HN', '+44(0)117 4960954', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(15, 'Bibi-Hayes', '11 Dylan square', 'Connorstad', 'S7 6NF', '(0131) 496 0551', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(16, 'Davies-Fisher', '1 Harris junctions', 'Ashleighchester', 'ME6 1RX', '+44(0)115 4960470', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(17, 'Russell Noble and Tomlinson', '941 Clifford highway', 'Simontown', 'UB0 2UZ', '+44(0)121 496 0720', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(18, 'Holmes-Baker', '7 Burrows islands', 'Oliverhaven', 'CR1E 8NL', '029 2018085', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(19, 'Smith Taylor and Greenwood', '45 Thornton crescent', 'East Graham', 'DH7 3WW', '(0151) 496 0911', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(20, 'Morgan Clarke and Butcher', '117 Kerry way', 'West Billymouth', 'CW26 3GP', '4.42E+11', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(21, 'Lawrence Inc', '017 Rhys fork', 'Edwardsfort', 'B7B 7RQ', '(0191) 4960418', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(22, 'Campbell Ryan and Ball', '789 Carpenter estates', 'South Barbaramouth', 'G37 7QG', '+44(0)1914960646', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(23, 'Dunn Barrett and Andrews', '450 Smith streets', 'Port Terry', 'DA6A 0JS', '(0151) 4960330', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(24, 'Watkins-Shah', '6 Jordan rapid', 'West Normanton', 'N1J 9BG', '44289018780', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(25, 'Robson PLC', '497 Howard park', 'Leesburgh', 'G0G 0BD', '+4429 2018 0277', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(26, 'Smith-Begum', '2 Norton rest', 'North Victor', 'B5T 5YY', '+44151 496 0870', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(27, 'Bishop Bell and Hayes', '50 Harrison crescent', 'Bartonville', 'L7F 8NE', '+44(0)1184960629', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(28, 'Bell Long and Dobson', '621 Lee mount', 'East Garethside', 'CR8E 7ZH', '+441632 960 169', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(29, 'Walker LLC', '94 Blackburn inlet', 'Taylorville', 'BH8 3ZT', '(01632) 960379', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(30, 'Bray-Jackson', '3 Lindsey ranch', 'Chloeton', 'B6J 9PD', '(020) 7496 0357', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(31, 'Davies-Harding', '41 Eileen course', 'Carolport', 'W2 2HN', '+44808 1570015', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(32, 'Watkins-Pope', '1 Nicole fork', 'Edwardtown', 'LU0B 9DE', '1174960070', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(33, 'Bond Evans and Barnett', '230 Robert crescent', 'Bellport', 'DN1V 6WR', '(0191)4960284', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(34, 'George Inc', '6 Elizabeth mountains', 'New Deborahside', 'JE1 6SH', '0114 496 0992', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(35, 'Parkinson-Cook', '43 Mills crossing', 'Jonesmouth', 'WN3 1ST', '2074960281', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(36, 'Jones-Owens', '67 Turner crossroad', 'South Leonard', 'W29 3LU', '(029)2018613', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(37, 'Atkins Vincent and Woods', '1 Barnes locks', 'New Sian', 'CF1 5BS', '0141 496 0917', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(38, 'Bowen Rhodes and Bird', '944 Owen prairie', 'Powertown', 'WC94 3QH', '(0161)4960610', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(39, 'Mellor Holloway and Lawrence', '42 Williams grove', 'Shaunberg', 'EN10 0US', '4.49E+11', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(40, 'Ahmed Morgan and Ashton', '477 Holmes bridge', 'East Deborahfurt', 'G8D 5EH', '(0161) 496 0913', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(41, 'Gray Group', '5 Richard greens', 'North Danielleland', 'M1W 0PG', '(0115) 4960710', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(42, 'Wells-Davey', '92 Clark shore', 'East Francesport', 'S7K 0SQ', '+44808 1570762', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(43, 'Cox-Whitehead', '6 Rogers curve', 'Janeland', 'CB8E 2PZ', '+44(0)20 74960949', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(44, 'Barton Cooper and Pratt', '7 Martyn loaf', 'New Davidside', 'B89 0FD', '+44808 157 0152', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(45, 'Evans Newton and Powell', '80 Dickinson roads', 'South Matthew', 'L2U 1UR', '(020) 74960086', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(46, 'Mitchell and Sons', '3 Gerard squares', 'Alisontown', 'NR4 8WT', '(0141) 496 0800', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(47, 'Ross Group', '49 Tucker camp', 'North Liam', 'E0 4TZ', '+44(0)909 879 0552', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(48, 'Evans-Burton', '7 Spencer trail', 'Port Eileenmouth', 'TF0N 9AF', '+44191 496 0024', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(49, 'Davies Group', '965 Norman drive', 'West Kirsty', 'SM0 7BE', '+44(0)116 496 0631', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(50, 'Morgan Hall and Baldwin', '772 Laura coves', 'Josephinebury', 'N1 3DG', '(0909) 879 0459', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(51, 'Horton PLC', '320 Helen turnpike', 'North Tina', 'DD89 0TL', '+441632 960 169', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(52, 'Wong Slater and Storey', '935 Simon oval', 'Katystad', 'DL11 6AP', '(028)9018587', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(53, 'Bailey and Sons', '79 Daniel unions', 'Connorstad', 'LS9 7DF', '+44(0)909 8790985', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(54, 'Jackson Townsend and Banks', '3 Gerald port', 'Lake Mitchellfurt', 'BA4 1TA', '0117 496 0567', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(55, 'Mann LLC', '685 Cooper plain', 'Lake Lydia', 'AL47 4JT', '+44(0)191 496 0294', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(56, 'Johnson Kelly and Bates', '55 Smith burgs', 'Gerardstad', 'SR6M 7FJ', '(0909) 8790721', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(57, 'Noble-Cox', '080 Warner junctions', 'West Fionatown', 'N4 3UB', '4.42E+11', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(58, 'Newman Khan and Hudson', '64 Moran mall', 'Lake Aaronside', 'N20 1NU', '+441632 960 169', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(59, 'Bradley LLC', '9 Christine forges', 'East Damienland', 'AB2 0JU', '4.42E+11', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(60, 'Wong-Dale', '48 Newman vista', 'New Caroline', 'S6S 0HW', '(0113)4960511', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(61, 'Oliver Inc', '5 Walker fords', 'North Sandrafurt', 'IV1A 4WS', '+44(0)117 496 0318', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(62, 'Kelly-Pollard', '055 Heath loaf', 'Guyview', 'CF47 6PG', '(0141) 496 0554', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(63, 'Thomas and Sons', '86 Long fork', 'New Maurice', 'ML4P 4EW', '+44(0)1632 960 568', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(64, 'Burns LLC', '157 Buckley heights', 'East Rhys', 'B51 2QY', '+44(0)1164960750', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(65, 'Bibi-Todd', '64 Martyn bridge', 'Brownland', 'N1 1GW', '(0151)4960832', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(66, 'Price James and Palmer', '73 Denise ferry', 'South Abigail', 'AL0 2NB', '1184960732', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(67, 'Russell PLC', '04 Lawrence throughway', 'Saraside', 'S4T 3BG', '(0151)4960717', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(68, 'Smith Inc', '254 Oliver spurs', 'Juliechester', 'E7 1AL', '+44(0)114 496 0686', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(69, 'Mason Winter and Griffiths', '82 Atkins drive', 'Port Maxberg', 'SW45 1RH', '(0113) 4960197', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(70, 'Webster-Middleton', '666 Marilyn estates', 'West Stewart', 'WS0M 8FU', '+44141 4960595', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(71, 'Carter Inc', '41 Claire groves', 'North Kevinmouth', 'L37 0BX', '(028)9018672', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(72, 'Webb Chapman and Cox', '6 Barrett pass', 'Ireneshire', 'SM0Y 5NU', '(0131) 4960154', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(73, 'Riley-Dean', '972 Clements lodge', 'Andreachester', 'N0W 9XQ', '+44(0)1614960261', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(74, 'Harrison LLC', '07 Scott harbor', 'New Billy', 'LL8 7JZ', '(0306) 999 0341', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(75, 'Hopkins and Sons', '273 Suzanne station', 'South Ritafurt', 'CT3 4WP', '+4428 9018670', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(76, 'Ferguson-Mason', '59 Davis ports', 'Parkerview', 'HA6 2QY', '+44131 4960905', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(77, 'Webster LLC', '3 Butcher haven', 'West Rebeccaview', 'SR0A 5FT', '(0116) 496 0074', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(78, 'Ward PLC', '778 Rhys glen', 'South Victoria', 'BL16 8UB', '(0113) 4960116', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(79, 'Jones-Porter', '80 Denis point', 'New Damian', 'B97 4UL', '(01632) 960 243', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(80, 'Hussain Butler and Robertson', '814 Brown fall', 'New Adrian', 'RH53 1FR', '+44(0)306 999 0135', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(81, 'Clayton-Hughes', '156 Josephine mall', 'Brettton', 'GY6R 6AT', '0114 4960747', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(82, 'Benson-Jones', '835 Hilton crossing', 'East Emily', 'G09 8AD', '(020) 7496 0603', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(83, 'Hughes Fry and Bentley', '1 Stewart estates', 'Hickstown', 'G81 6YG', '(0808) 1570252', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(84, 'Barrett-Wilson', '646 Neil springs', 'Lake Daniel', 'MK4R 2BA', '0151 4960222', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(85, 'Rose Bell and Brown', '14 Janet village', 'East Frederickborough', 'GL4 6LR', '(0191)4960062', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(86, 'Smith PLC', '970 Fox trail', 'New Michael', 'EX87 8TF', '1144960127', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(87, 'Taylor Group', '6 Collins creek', 'South Justinfort', 'G22 3RG', '+44113 496 0060', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(88, 'Baker Hawkins and Webster', '05 Jonathan forest', 'Julianshire', 'G7T 4ET', '(0141) 4960473', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(89, 'Roberts-Harper', '70 Davies islands', 'Brownville', 'SN5R 6WE', '(0808) 1570773', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(90, 'Lane Thomas and Green', '404 Robin lakes', 'West Dorothyside', 'E62 6RU', '+44(0)118 4960928', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(91, 'Doherty-Marshall', '71 Margaret falls', 'Gregoryburgh', 'NP45 2LJ', '(028)9018463', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(92, 'Clarke Smith and Edwards', '2 Turner wall', 'Port Colin', 'S0 9LJ', '(0117) 496 0399', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(93, 'Rahman-Bartlett', '609 Miller plaza', 'Jadehaven', 'ME94 4HP', '+44(0)117 4960853', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(94, 'Jones-Smart', '5 Grant corner', 'West Nigelborough', 'G09 3TT', '+441632 960 169', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(95, 'Mitchell-Davies', '661 Warren via', 'South Melanie', 'W45 7HS', '+44(0)113 4960987', 'solicitor');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(96, 'Griffiths Wilson and Ward', '9 Donnelly burgs', 'South Matthewfurt', 'BD1H 3BP', '028 9018019', 'charity');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(97, 'Hill Gibson and Wade', '2 Timothy wall', 'North Tracy', 'TA27 6WY', '+44121 4960181', 'mediation');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(98, 'Lee Russell and Stephenson', '826 Victor lights', 'West Gemmamouth', 'NN6 9PP', '+44115 4960998', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(99, 'Wilson-Morris', '08 Michelle lakes', 'South Stephanie', 'M2 7FY', '(0118) 496 0735', 'private');
INSERT INTO ADVISER (id, name, address1, city, postcode, phone, org_type) Values(100, 'Taylor Wallis and Hall', '53 Smith street', 'Janetmouth', 'BL41 9PL', '(0117) 4960979', 'private');



INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(1,1, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(2,2, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(3,2, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(4,2, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(5,3, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(6,3, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(7,3, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(8,3, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(9,4, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(10,4, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(11,4, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(12,4, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(13,5, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(14,5, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(15,6, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(16,6, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(17,7, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(18,7, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(19,7, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(20,8, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(21,8, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(22,8, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(23,8, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(24,9, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(25,9, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(26,10, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(27,10, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(28,10, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(29,11, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(30,11, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(31,12, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(32,12, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(33,12, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(34,12, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(35,15, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(36,16, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(37,16, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(38,16, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(39,16, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(40,17, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(41,17, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(42,17, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(43,18, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(44,19, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(45,23, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(46,24, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(47,24, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(48,24, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(49,24, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(50,25, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(51,25, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(52,25, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(53,25, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(54,26, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(55,26, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(56,27, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(57,28, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(58,28, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(59,29, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(60,29, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(61,29, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(62,30, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(63,31, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(64,31, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(65,31, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(66,32, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(67,32, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(68,33, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(69,33, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(70,34, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(71,34, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(72,34, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(73,35, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(74,35, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(75,35, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(76,35, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(77,36, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(78,36, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(79,37, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(80,38, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(81,38, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(82,38, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(83,39, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(84,39, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(85,39, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(86,40, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(87,41, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(88,41, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(89,42, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(90,42, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(91,42, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(92,42, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(93,43, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(94,43, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(95,43, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(96,43, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(97,44, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(98,44, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(99,45, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(100,45, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(101,46, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(102,47, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(103,47, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(104,49, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(105,49, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(106,49, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(107,50, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(108,50, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(109,51, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(110,53, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(111,53, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(112,53, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(113,53, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(114,54, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(115,54, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(116,55, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(117,55, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(118,55, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(119,55, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(120,56, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(121,56, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(122,56, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(123,56, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(124,57, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(125,57, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(126,58, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(127,58, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(128,58, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(129,59, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(130,59, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(131,59, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(132,60, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(133,60, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(134,60, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(135,61, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(136,61, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(137,61, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(138,62, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(139,62, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(140,63, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(141,63, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(142,64, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(143,64, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(144,64, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(145,64, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(146,65, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(147,65, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(148,65, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(149,65, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(150,66, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(151,66, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(152,66, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(153,66, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(154,67, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(155,67, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(156,68, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(157,68, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(158,69, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(159,69, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(160,70, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(161,70, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(162,70, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(163,72, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(164,73, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(165,73, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(166,73, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(167,74, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(168,75, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(169,75, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(170,76, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(171,76, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(172,77, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(173,78, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(174,78, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(175,79, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(176,79, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(177,79, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(178,80, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(179,80, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(180,81, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(181,81, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(182,81, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(183,82, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(184,82, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(185,83, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(186,83, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(187,83, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(188,83, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(189,84, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(190,84, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(191,84, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(192,85, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(193,85, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(194,86, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(195,86, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(196,86, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(197,87, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(198,87, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(199,87, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(200,88, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(201,88, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(202,88, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(203,89, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(204,89, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(205,89, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(206,89, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(207,90, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(208,90, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(209,91, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(210,92, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(211,92, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(212,92, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(213,93, 'cat_crime');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(214,93, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(215,93, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(216,95, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(217,95, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(218,95, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(219,96, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(220,96, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(221,97, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(222,98, 'cat_debt');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(223,98, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(224,98, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(225,99, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(226,99, 'cat_immigration_or_asylum');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(227,99, 'cat_welfare_benefits');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(228,100, 'cat_housing');
INSERT INTO CATEGORY (ID, ADVISER_ID, NAME) VALUES(229,100, 'cat_immigration_or_asylum');